import type { ITodo } from "@interfaces/ITodo";

export const SAMPLE_TODOS: ITodo[] = [{
    id: 1,
    title: "Sample Todo",
    description: "This is a sample todo item.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "Medium",
  },
  {
    id: 2,
    title: "Another Todo",
    description: "This is another sample todo item.",
    completed: true,
    createdOn: new Date(),
    updatedOn: new Date(),
    completedOn: new Date(),
    importance: "High",
  },
  {
    id: 3,
    title: "Third Todo",
    description: "This is the third sample todo item.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "Low",
  },
  {
    id: 4,
    title: "Buy Groceries",
    description: "Get milk, bread, eggs, and vegetables.",
    completed: true,
    createdOn: new Date(),
    updatedOn: new Date(),
    completedOn: new Date(),
    importance: "Medium",
  },
  {
    id: 5,
    title: "Finish Project Report",
    description: "Complete the quarterly project report for presentation.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "High",
  },
  {
    id: 6,
    title: "Call Mom",
    description: "Check in with mom and catch up.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "Medium",
  },
  {
    id: 7,
    title: "Schedule Dentist Appointment",
    description: "Book appointment for routine checkup.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "High",
  },
  {
    id: 8,
    title: "Review Code Changes",
    description: "Review pull requests from team members.",
    completed: true,
    createdOn: new Date(),
    updatedOn: new Date(),
    completedOn: new Date(),
    importance: "High",
  },
  {
    id: 9,
    title: "Plan Weekend Trip",
    description: "Research and plan destination for weekend getaway.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "Low",
  },
  {
    id: 10,
    title: "Update Documentation",
    description: "Update API documentation with new endpoints.",
    completed: false,
    createdOn: new Date(),
    updatedOn: null,
    completedOn: null,
    importance: "Medium",
  }]